FROM python:3.12.1
WORKDIR /app

COPY ./requirements.txt ./app.py ./config.py ./model.py ./app.db ./
COPY ./routes ./routes
RUN pip install -r ./requirements.txt

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "app:create_app()"]